name: Update Google Calendar

on: 
  schedule:
    - cron: "0 * * * *"   # 매 시간마다 실행
  workflow_dispatch:       # 수동 실행 가능
  push:
    paths:
      - 'scripts/**'       # scripts 폴더 변경 시 실행

jobs:
  update-calendar:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run script
        run: python scripts/update_readme.py
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
          GOOGLE_CALENDAR_ID: ${{ secrets.GOOGLE_CALENDAR_ID }}


      - name: Commit changes
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "github-actions"
          git add README.md
          git commit -m "Update README with Google Calendar events" || echo "No changes to commit"
          git push https://x-access-token:${{ secrets.GH_PAT }}@github.com/${{ github.repository }}.git


